version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: $ENCODED_KEYSTORE | base64 --decode --ignore-garbage >> ${HOME}/keystore
      - run: cat 'export KEYSTORE=${HOME}/keystore' >> $BASH_ENV
      - run: $DEPLOYMENT_PRIVATE_KEY | base64 --decode --ignore-garbage >> ${HOME}/deployment_private_key.json
      - run: cat 'export PRIVATE_KEY=${HOME}/deployment_private_key.json' >> $BASH_ENV
      - run:
          name: Upload to Google Play
          command: ./gradlew publishRelease

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - build
            - tests
          filters:
            branches:
              only:
                - master
